### ISSUE TITLE
Screenshots or Gifs

### ISSUE THREAD

**Issue by daviddias** [marcin212/ipfs-gui#1]
Hi @marcin212! This looks cool :)

Mind adding a screenshot or a gif of the UI? I would love to see how it looks without having to install a windows vm :) Thanks!

**Comment by marcin212** [comment]
@diasdavid 
![tray](https://img.bymarcin.com/2017-08-17_10-50-16_KsJ0F90zv45L4s4q.png)
![sendto](https://img.bymarcin.com/2017-08-17_10-50-58_MPyUHCnpe4hEREmv.png)
![ballon](https://img.bymarcin.com/2017-08-17_10-51-23_wR4i7YJYoxRpNkMS.png)

**Comment by marcin212** [comment]
![app](https://img.bymarcin.com/2017-08-17_11-04-14_PkXCLifarr5oYmN6.gif)

**Comment by marcin212** [comment]
![installator](https://img.bymarcin.com/2017-08-17_11-14-18_xrwW1oEG04JY3D8E.gif)

**Comment by daviddias** [comment]
Thank you @marcin212 :) I like where this is going!
